use_frameworks!

platform :ios, '12.0'

target 'SFServiceKit_Example' do
  pod 'SFServiceKit', :path => '../'

  target 'SFServiceKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
